name: NPM Publish

on:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Setup protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "25.1"

      - name: Install dependencies
        run: npm ci

      - name: Create generated directory
        run: mkdir -p generated

      - name: Generate TypeScript from protobuf
        run: npm run generate

      - name: Build TypeScript
        run: npm run compile

      - name: Run tests (if any)
        run: npm test --if-present

      - name: Get current version
        id: version
        run: echo "current_version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
